apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgres
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 125Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/postgresVolume"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres
spec:
  storageClassName: manual
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: danutbuse/postgres-gestiune:1.2
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: storage
              mountPath: /data/base
          env:
            - name: POSTGRES_PASSWORD
              value: password
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: pvc-postgres
  